### ISSUE TITLE
[BUG] No config file detected after making the build

### ISSUE THREAD

**Issue by tarun1992** [nielsdejong/neodash#91]
When making a new build in standalone mode using 'npm run build', below error is coming in the console - 

![image](https://user-images.githubusercontent.com/4682201/154977352-2e65b568-7e12-48a5-8779-3f2ebf7ed70a.png)

Please help in resolving the issue. I am using windows to make the build.

**Comment by nielsdejong** [comment]
Hi @tarun1992 ,

Are you hosting the site on a sub-directory of a domain by any chance?
There was minor issue caused NeoDash to not work on subdirectories (e.g. http://neodash.graphapp.io/test/) but only on the main host (http://neodash.graphapp.io).

If yes, I fixed it here, but it is not out with a release yet: https://github.com/nielsdejong/neodash/commit/8166c13861f9ab293ed74f9324ef3c2b665ffe3a#diff-c72fc7c8e9039f8edb72e166659f7f83f999289acb94ffd9bf2e51d0db8ade9fR181 

If no, are you able to access {YOUR URL}/config.json in your web browser?

**Comment by tarun1992** [comment]
I am able to access the file in my web browser - seems to me a different issue as in below screenshot - 

![image](https://user-images.githubusercontent.com/4682201/155273426-cc33a2e2-9ea2-4400-8922-01560d0e1441.png)

I think chrome is restricting the direct access the config file.

**Comment by nielsdejong** [comment]
hi @tarun1992 - when we last spoke you mentioned you might have a fix for this issue? or does this still persist - if yes, could you give me a description of how you produce the error?
We're getting the 2.1 release out on Thursday, so would be great if we can get this to be resolved.

Thank you,
Niels

**Comment by tarun1992** [comment]
Hello @nielsdejong - the issue still persists. This can be replicated using the build version of the project(npm run build). After that try to deploy on any server or run index.html. You will see the error in the console of no config file detected.

I implemented an alternative to solve this particular problem where I fetch config file before we build the project and then it doesn't have to fetch every time.

**Comment by nielsdejong** [comment]
Hi Tarun,

For me I get a different behaviour depending on how I run the app:
- If I build the project, and deploy the entire `dist` folder to a webserver, so much error appears. The app is correctly able to find `config.json`.
- If I open the `index.html` file directly in a browser, I do get the issue where it cannot find `config.json` plus a warning:
```
Access to internal resource at 'file:///Users/nielsdejong/Desktop/Code/neodash/dist/manifest.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
```
This is expected, as when you're opening a file directly, the browser does not let you read other files from disk (Security reasons). 

What is strange however is that it even gives you the warning when you deploy it to a webserver.  Could you double check whether you deployed the entire folder (and not just index.html)? And possibly send a screenshot of the error you see when deployed to a webserver?

Thanks for your patience,
Niels

**Comment by tarun1992** [comment]
Sure, I will try to check again after deploying and share a screenshot.

**Comment by tarun1992** [comment]
Hello @nielsdejong, issue is resolved after redeploying. I think its due to some server issue which was blocking the access of config.json file on my end.
